export const CANDIDATES = [
  {
    id: 'lula',
    number: '13',
    name: 'Luiz Inácio Lula da Silva',
    short: 'Lula',
    party: 'PT',
    color: '#D00027',
    photo: '/candidatos/lula.jpg',
    style: { gender: 'm', skin: '#e8b98a', hair: 'bald', hairColor: '#c7c7c7', glasses: false, beard: true, tie: '#FFDF00' },
  },
  {
    id: 'flavio-bolsonaro',
    number: '22',
    name: 'Flávio Bolsonaro',
    short: 'Flávio Bolsonaro',
    party: 'PL',
    color: '#2A3B8F',
    photo: '/candidatos/flavio-bolsonaro.jpg',
    style: { gender: 'm', skin: '#f0c29a', hair: 'short', hairColor: '#2c2c2c', glasses: false, beard: false, tie: '#4a6cc3' },
  },
  {
    id: 'caiado',
    number: '55',
    name: 'Ronaldo Caiado',
    short: 'Caiado',
    party: 'PSD',
    color: '#0B5BA5',
    photo: '/candidatos/caiado.jpg',
    style: { gender: 'm', skin: '#f2c9a4', hair: 'short', hairColor: '#6f6f6f', glasses: false, beard: false, tie: '#123c74' },
  },
  {
    id: 'renan-santos',
    number: '90',
    name: 'Renan Santos',
    short: 'Renan Santos',
    party: 'Missão',
    color: '#6C3AB8',
    photo: '/candidatos/renan-santos.jpg',
    style: { gender: 'm', skin: '#8d5a3b', hair: 'short', hairColor: '#1e1e1e', glasses: false, beard: false, tie: '#FFDF00' },
  },
  {
    id: 'zema',
    number: '30',
    name: 'Romeu Zema',
    short: 'Zema',
    party: 'Novo',
    color: '#F5821F',
    photo: '/candidatos/zema.jpg',
    style: { gender: 'm', skin: '#e9bd92', hair: 'short', hairColor: '#d8d8d8', glasses: false, beard: false, tie: '#f5821f' },
  },
  {
    id: 'marcal',
    number: '28',
    name: 'Pablo Marçal',
    short: 'Marçal',
    party: 'PRTB',
    color: '#1B9E4B',
    photo: '/candidatos/marcal.png',
    style: { gender: 'm', skin: '#e6b58a', hair: 'curly', hairColor: '#1a1a1a', glasses: false, beard: false, tie: '#1b9e4b' },
  },
  {
    id: 'edmilson-costa',
    number: '21',
    name: 'Edmilson Costa',
    short: 'Edmilson Costa',
    party: 'PCB',
    color: '#C8102E',
    photo: '/candidatos/edmilson-costa.jpg',
    style: { gender: 'm', skin: '#7a4a2c', hair: 'curly', hairColor: '#141414', glasses: false, beard: true, tie: '#c8102e' },
  },
  {
    id: 'cury',
    number: '70',
    name: 'Augusto Cury',
    short: 'Augusto Cury',
    party: 'Avante',
    color: '#0E7C86',
    photo: '/candidatos/cury.jpg',
    style: { gender: 'm', skin: '#f0c19a', hair: 'medium', hairColor: '#b9b9b9', glasses: false, beard: false, tie: '#0e7c86' },
  },
  {
    id: 'barao',
    number: '27',
    name: 'Clariana Barão',
    short: 'Clariana Barão',
    party: 'DC',
    color: '#3A5BA0',
    photo: '/candidatos/barao.jpg',
    style: { gender: 'f', skin: '#f2cba6', hair: 'long', hairColor: '#3a2417', glasses: false, beard: false, tie: '#3a5ba0' },
  },
  {
    id: 'hertz-dias',
    number: '16',
    name: 'Hertz Dias',
    short: 'Hertz Dias',
    party: 'PSTU',
    color: '#B3001B',
    photo: '/candidatos/hertz-dias.jpg',
    style: { gender: 'm', skin: '#eec49e', hair: 'short', hairColor: '#333333', glasses: true, beard: false, tie: '#b3001b' },
  },
  {
    id: 'pimenta',
    number: '29',
    name: 'Rui Costa Pimenta',
    short: 'Rui Costa Pimenta',
    party: 'PCO',
    color: '#A00000',
    photo: '/candidatos/pimenta.jpg',
    style: { gender: 'm', skin: '#ecd2b0', hair: 'medium', hairColor: '#a9a9a9', glasses: false, beard: true, tie: '#a00000' },
  },
  {
    id: 'samara-martins',
    number: '80',
    name: 'Samara Martins',
    short: 'Samara Martins',
    party: 'UP',
    color: '#8E1E3C',
    photo: '/candidatos/samara-martins.jpg',
    style: { gender: 'f', skin: '#b97a4d', hair: 'medium', hairColor: '#22140c', glasses: false, beard: false, tie: '#8e1e3c' },
  },
  {
    id: 'wilson-grassi',
    number: '10',
    name: 'Wilson Grassi',
    short: 'Wilson Grassi',
    party: 'Democrata',
    color: '#123C74',
    photo: '/candidatos/wilson-grassi.jpg',
    style: { gender: 'm', skin: '#ecc7a0', hair: 'short', hairColor: '#8a8a8a', glasses: false, beard: false, tie: '#123c74' },
  },
];

export function getCandidate(id) {
  return CANDIDATES.find((c) => c.id === id);
}

export function formatBRL(value) {
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value || 0);
}

export function formatCompact(value) {
  return new Intl.NumberFormat('pt-BR', { notation: 'compact', maximumFractionDigits: 1 }).format(value || 0);
}
